name: Build and Dev Deploy
on: 
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        env:
          GITHUB_PAGES: "true"
        run: |
          npm install
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true